name: Run Run Run

on:
  schedule:
    - cron: '37 1,7,10,12,14,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        
      - name: Cache token
        uses: actions/cache@v3
        with:
          path: encrypted_tokens.data
          key: token-cache-${{ github.sha }}
          restore-keys: |
            token-cache-
            
      - name: Init Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          
      - name: Start
        env:
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py
